### PR TITLE
fix(preset-uno): `animate-*` stuff

### LINKED ISSUE #170: feat(preset-uno): `animate-*` stuff

### PR DESCRIPTION
**Pull request by chris-zhu**
[https://github.com/antfu/unocss/issues/170](https://github.com/antfu/unocss/issues/170)

I find animate rules depend on [https://github.com/animate-css/animate.css](https://github.com/animate-css/animate.css), some animate rules are different from tw and windi.

For example, 
```
// tw and windi
@keyframes pulse {   
  0%, 100% {     opacity: 1;   } 
  
  50% {     opacity: .5;   } 
}
```

```
// animate.css
@keyframes pulse {
  from {
    transform: scale3d(1, 1, 1);
  }

  50% {
    transform: scale3d(1.05, 1.05, 1.05);
  }

  to {
    transform: scale3d(1, 1, 1);
  }
}
```

So, some rules are not align with tailwindcss and windicss

closes #170

### CODE REVIEW

File: packages/preset-uno/src/rules/animation.ts [hunk 1]
```diff
@@ -104,11 +104,69 @@ const keyframes: Record<string, string> = {
...
+}
+
 export const animations: Rule[] = [
   [/^animate-(.*)$/, ([, name], { constructCSS }) => {
     const kf = keyframes[name]
-    if (kf)
-      return `@keyframes ${name}${kf}\n${constructCSS({ animation: `${name} 1s linear infinite` })}`
+    if (kf) {
+      return `@keyframes ${name}${kf}\n${constructCSS(
+        Object.assign({ animation: `${name} ${durations[name]} ${timingFns[name]} ${iterations[name]}` }, properties[name]))}`
```
Comment (antfu) [inline packages/preset-uno/src/rules/animation.ts:168]: Could we assign the default value here instead of in the map to save some memory?

Meaning:
`${durations[name] || '1s'}`

Comment (chris-zhu) [reply packages/preset-uno/src/rules/animation.ts]: Of course
